### ISSUE TITLE
Github集成Travis CI

### ISSUE THREAD

**Issue by levy9527** [levy9527/blog#1]
# 前言
已经有阮一峰老师的[持续集成服务 Travis CI 教程](http://www.ruanyifeng.com/blog/2017/12/travis_ci_tutorial.html)，为什么还要写这篇文章？

原因有二：
1. 文章内容有些过时
1. 文章覆盖度不够，有些实践细节没写出来

由于以上原因，纵然可以笔者很快在Github集成Travis CI并成功构建，但在发布时却踩了一些坑，一直失败，折腾一波才终于发布成功。故写下此文，旨在补充更多的细节，帮助他人少走弯路。

<a name="58378f0d"></a>
# 正文
<a name="0104ba5d"></a>
## 免费购买Travis CI应用
点击 [https://github.com/marketplace/travis-ci](https://github.com/marketplace/travis-ci)，登录后免费购买(开源项目集成Travis CI不收费)。

<a name="8dfdf567"></a>
## 选择关联仓库
选择个人或组织名下需要关联Travis CI的Github仓库。

已经设置过的，想进行修改，可以在Github的 Personal settings-> Applications 中进入。<br />![](https://cdn.nlark.com/yuque/0/2019/png/160590/1552699916365-0a309745-c830-480e-8c8f-58b2dde3f7bc.png#align=left&display=inline&height=285&originHeight=381&originWidth=227&size=0&status=done&width=170)![image.png](https://cdn.nlark.com/yuque/0/2019/png/160590/1552695398638-13ec5516-3002-4a74-bf08-099b32f2b612.png#align=left&display=inline&height=259&name=image.png&originHeight=958&originWidth=1992&size=408088&status=done&width=538)<br />
![image.png](https://cdn.nlark.com/yuque/0/2019/png/160590/1552695750384-cc7d516e-c10d-4553-8811-84ac13f3ee4f.png#align=left&display=inline&height=316&name=image.png&originHeight=632&originWidth=1340&size=207631&status=done&width=670)
<a name="96af7003"></a>
## 编写CI文件
在项目根目录下新建 `.travis.yml` 文件

```bash
touch .travis.yml
```

下面是一个实际使用的例子，可以直接复制粘贴使用。<br />该示例包含了：
* 指定node.js版本
* 使用yarn进行安装依赖及构建
* 对安装需要的依赖进行了缓存
* 设置了两个不含敏感信息的环境变量
* 设置了一个含有敏感信息的环境变量
* 把构建生成的文件部署至github pages

```yaml
language: node_js
node_js:
- lts/*
env:
- API_SERVER=https://easy-mock.com/mock/5c1b3895fe5907404e654045/femessage-mock PUBLIC_PATH=http://levy.work/nuxt-element-dashboard/
install:
- yarn
script:
- yarn build
cache: yarn
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  local-dir: dist
  on:
    branch: master
  github-token: $GITHUB_TOKEN
```

下面对文件进行说明。

```yaml
language: node_js
node_js:
- lts/*
```

* 第1行指定了构建环境为node.js
* 第2、3行指定使用node.js最新的LTS版本

```yaml
env:
- API_SERVER=xxx PUBLIC_PATH=xxx
```

上面是设置两个环境变量。

注意，一次构建中传多个环境变量，必须写在同一行，使用空格分开。

```yaml
env:
- API_SERVER=xxx 
- PUBLIC_PATH=xxx
```

如果写成上面的形式，则会变成两个构建，每一个构建中只有一个环境变量。

```yaml
install:
- yarn
script:
- yarn build
cache: yarn
```

上面指定使用yarn进行安装依赖，安装好后执行 `yarn build` 命令; 为yarn的依赖加速安装，开启了缓存。

下面是最关键的部署配置。

```yaml
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  local-dir: dist
  on:
    branch: master
  github-token: $GITHUB_TOKEN
```

* 第2行指定部署到Github Pages，即仓库的 `gh-pages` 分支，请确保仓库的pages分支是 `gh-pages` , [相关操作可以看这里](#b637c71e)
* 第3行指定保留构建后的文件
* 第4行指定每次部署会新增一个提交记录再推送，而不是使用 `git push --force` 
* 第5行指定构建后要部署的目录
* 第6、7行指定 `master` 分支有提交行为时，将触发构建后部署
* 第8行是部署需要用到的`github-token`,其中`$GITHUB_TOKEN`是变量，它可以在Travis CI个人仓库的setting页里设置，[相关操作可以看这里](#74ae38aa)

<a name="4ece5573"></a>
## 相关操作
<a name="b637c71e"></a>
### GitHub Pages
查看`gh-pages`分支的部署情况

进入仓库 Settings -> Options<br />
![image.png](https://cdn.nlark.com/yuque/0/2019/png/160590/1552699596402-08204f8a-5f36-4986-abb7-e0b3eaa7ab6e.png#align=left&display=inline&height=100&name=image.png&originHeight=200&originWidth=1606&size=114488&status=done&width=803)

往下翻看，可以看到效果<br />![image.png](https://cdn.nlark.com/yuque/0/2019/png/160590/1552699631605-7b018c4a-9e4f-4405-9423-9345f3ab16e3.png#align=left&display=inline&height=244&name=image.png&originHeight=488&originWidth=1380&size=278744&status=done&width=690)<br />因为笔者自定义了域名，所以地址不是默认的 https://xxx.github.io/xxx

<a name="74ae38aa"></a>
### 设置GITHUB_TOKEN
首先为Travis CI新建一个token<br />![](https://cdn.nlark.com/yuque/0/2019/png/160590/1552699916365-0a309745-c830-480e-8c8f-58b2dde3f7bc.png#align=left&display=inline&height=285&name=&originHeight=381&originWidth=227&status=done&width=170)![](https://cdn.nlark.com/yuque/0/2019/png/160590/1552699974567-7208da19-fdb5-4c43-b19b-61acfb4c4783.png#align=left&display=inline&height=184&name=&originHeight=184&originWidth=254&size=0&status=done&width=254)[](https://help.github.com/assets/images/help/settings/personal_access_tokens_tab.png)![](https://cdn.nlark.com/yuque/0/2019/png/160590/1552700133575-16c48b5a-fe9c-4eb4-a6ab-cf4e066d5881.png#align=left&display=inline&height=204&name=&originHeight=204&originWidth=262&size=0&status=done&width=262)<br />点击生成新token<br />[](https://help.github.com/assets/images/help/settings/generate_new_token.png)![](https://cdn.nlark.com/yuque/0/2019/png/160590/1552700229186-44a679d9-254f-4377-94bd-ac115e345cec.png#align=left&display=inline&height=64&name=&originHeight=82&originWidth=961&size=0&status=done&width=746)<br />设置权限<br />
![image.png](https://cdn.nlark.com/yuque/0/2019/png/160590/1552700351510-569e8cad-ecc4-420a-a7c0-d94cf87a6632.png#align=left&display=inline&height=516&name=image.png&originHeight=1032&originWidth=1228&size=598324&status=done&width=614)<br />复制生成的token。(记得先不要刷新或离开当前页面，否则token就看不见了，只能重新生成)

登录Travis CI, 进入要集成的项目设置页。<br />
![image.png](https://cdn.nlark.com/yuque/0/2019/png/160590/1552700606763-80259a22-e30e-474e-ae50-c31958367f1f.png#align=left&display=inline&height=348&name=image.png&originHeight=696&originWidth=2540&size=434279&status=done&width=1270)

添加环境变量`GITHUB_TOKEN`

注意，这里的环境变量是通过bash设置、并在.yml里读取的，所以变量名是大写加下划线形式，这是bash的最佳实践，千万别写成`github-token`

![image.png](https://cdn.nlark.com/yuque/0/2019/png/160590/1552700692945-dc8dc616-6829-4c2b-afae-9150ba001398.png#align=left&display=inline&height=300&name=image.png&originHeight=600&originWidth=1906&size=226858&status=done&width=953)

好了，在master分支上推送一下，试试新鲜出炉的CI服务吧！
